version: 2

models:
  - name: int__acceptance__country
    description: Table represents all unique country on dimension
    columns:
      - name: id
        description: Unique ID to countrys
        tests:
          - unique
          - not_null